[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hello_world = "DJi3QRBw25uLHk9XGSi18XyEQoxH37LkTVUjAeG9R8Ad"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
