[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fee_manager = "BnhW54yM9hZ1pFjfEkZePiniD6TZjGgRLjYqP6dFhCNQ"

[programs.devnet]
fee_manager = "BnhW54yM9hZ1pFjfEkZePiniD6TZjGgRLjYqP6dFhCNQ"

[programs.mainnet]
fee_manager = "BnhW54yM9hZ1pFjfEkZePiniD6TZjGgRLjYqP6dFhCNQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
